image:
  repository: artifactory.dagility.com/docker/vdcheckpz-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckpz-backend-default.dagility.com
    paths:
    - /
serviceAccount:
  create: false
